import time
from rp.place import *
from rp.transition import *
p = [
    Place(0, 0, 'lidsConveyor'),
    Place(1, 1, 'Lids Emitter'),
    Place(2, 0, 'basesConveyor'),
    Place(3, 0, 'Bases Emitter'),
    Place(4, 0, 'lidAtPlace'),
    Place(5, 0, 'clampLid'),
    Place(6, 0, 'lidClamped'),
    Place(7, 0, 'moveZ'),
    Place(8, 0, 'movingZ'),
    Place(9, 0, 'grab'),
    Place(10, 0, 'moveX'),
    Place(11, 0, 'movingX'),
    Place(12, 1, 'bf1'),
    Place(13, 0, 'Base at place'),
    Place(14, 0, 'bfb1'),
    Place(15, 0, 'Clamp base'),
    Place(16, 0, 'Base clamped'),
    Place(17, 0, 'bfb2'),
    Place(18, 0, 'bf3'),
    Place(19, 0, 'p19'),
    Place(20, 0, 'p20'),
    Place(21, 0, 'p21'),
    Place(22, 0, 'Pos. raise (bases)'),
    Place(23, 0, 'p23'),
    Place(24, 0, 'Pos limit (bases)'),
    Place(25, 0, 'p25'),
]

t = [
    Transition(0,
               [p[1]],
               [p[0]]),
    Transition(1,
               [p[0], p[12]],
               [p[0], p[4]]),
    Transition(2,
               [p[4], p[0]],
               [p[4], p[5]]),
    Transition(3,
               [p[5]],
               [p[6]]),
    Transition(4,
               [p[6]],
               [p[7], p[8]]),
    Transition(5,
               [p[7], p[8], p[18]],
               [p[7], p[9]]),
    Transition(6,
               [p[7], p[9], p[4]],
               [p[9], p[8]]),
    Transition(7,
               [p[8], p[9], p[18]],
               [p[9], p[10], p[11]]),
    Transition(8,
               [p[10], p[11]],
               [p[10], p[7], p[8]]),
    Transition(9,
               [p[7], p[9],  p[10], p[8]],
               [p[7], p[10], p[19]]),
    Transition(10,
               [p[19], p[7]],
               [p[8], p[20]]),
    Transition(11,
               [p[8], p[20]],
               [p[12]]),
    Transition(12,
               [p[21], p[23]],
               [p[22]]),
    Transition(13,
               [p[22], p[25]],
               [p[22], p[24]]),
    Transition(14,
               [p[24]],
               [p[25]]),
    Transition(15,
               [p[3]],
               [p[25]]),
    Transition(16,
               [p[25], p[14]],
               [p[25], p[13]]),
    Transition(17,
               [p[13], p[25]],
               [p[15]]),
    Transition(18,
               [p[15], p[17]],
               [p[16]]),
    Transition(19,
               [p[15], p[16]],
               [p[23]]),
]
